name: Tutor k8s print config.yml
description: Github Action to print the contents of tutor's config.xml to the
branding:
  icon: 'cloud'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - name: Dump tutor config.yml
      shell: bash
      continue-on-error: true
      run: |-
        echo 'config.yml:'
        echo '-------------------------------------'
        cat $(tutor config printroot)/config.yml
